### ISSUE TITLE
Would you like to migrate this repository into the cerebro organization? 

### ISSUE THREAD

**Issue by oguhpereira** [cerebroapp/cerebro-fix-path#2]
We are centralizing cerebro plugins in the product organization. It would be great to have this repository within the organization, to be part of the future plugin marketplace. If you are interested, we can create a team so that you can work directly on the project and help us grow this product.

See more https://github.com/cerebroapp

**Comment by cades** [comment]
> We are centralizing cerebro plugins in the product organization. It would be great to have this repository within the organization, to be part of the future plugin marketplace. If you are interested, we can create a team so that you can work directly on the project and help us grow this product.
> 
> 
> 
> See more https://github.com/cerebroapp

Thanks for reaching out! I think it's great to move this repo into the organization!

**Comment by oguhpereira** [comment]
I just added you as owner on the team so you can move this repository

**Comment by cades** [comment]
Hi @oguhpereira, I just transferred this repo to cerebroapp.
